name: Label requires reviews
author: TravelPerk <engineering@travelperk.com>
description: This Github action will require a minimum number of reviews if a label is present.
runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
  
  
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
  
  
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  rules_yaml:
    description: >
        YAML file with the rules to apply. The file should be in the format:
        ```
        <label>: <number of reviews>
        ```
        For example:
        ```
        typescript: 2
        migration: 5
        ```
branding:
  icon: 'user-check'  
  color: 'green'
