# legacy-peer-deps=true (closest equivalent in pnpm)
strictPeerDependencies: false # (this is already pnpm's default)

# pnpm controls this via savePrefix; empty string means “save exact” (no ^/~ prefix).
savePrefix: ""
nodeLinker: hoisted

minimumReleaseAgeExclude:
  - "undici@6.24.0" # Required for vulnerabiliti mitigation. Remove after 25/04/26
  - "minimatch@9.0.7" # Required for vulnerabiliti mitigation. Remove after 25/04/26
  - "flatted@3.3.4" # Required for vulnerabiliti mitigation. Remove after 25/04/26
  - "serialize-javascript@7.0.3" # Required for vulnerabiliti mitigation. Remove after 25/04/26

# pnpm v10 can block install scripts unless explicitly allowed.
allowBuilds:
  husky: true
